---
name: configure_policy_map_class
pack: network_essentials 
runner_type: python-script
description: This creates the Policy Map, Class Instance and Police Configurations.
enabled: true
entry_point: configure_policy_map_class.py
parameters:
  mgmt_ip:
    type: string
    description: The management IP address of the target device.
    required: true
    position: 0
  username:
    type: string
    description: The login user name to connect to the device.
    default: admin
    position: 1
  password:
    type: string
    description: The login password to connect to the device.
    default: password
    secret: true
    position: 2
  policy_map_name:
    type: string
    description: The Policy Map Class Name (Max Size -64).
    required: true
    position: 3
  class_name:
    type: string
    description: The Policy Map Class Name (Max Size -64).
    default: default 
    position: 4
  cir:
    type: integer
    description: The Committed Information Rate. The Valid Range is <0-300000000000> bits Per Second.
    position: 5
  cbs:
    type: integer 
    description: The Committed Burst Rate. The Valid Range is <1250-37500000000> Bytes.
    position: 6
  eir:
    type: integer 
    description: The Extended Information Rate. The Valid Range is <0-300000000000> bits Per Second.
    position: 7
  ebs:
    type: integer 
    description: The Extended Burst Rate. The Valid Range is <1250-37500000000> Bytes. 
    position: 8
