---
name: configure_bridge_domain
pack: network_essentials
runner_type: python-script
description: This will create the bridge domain for p2mp/p2p and bind the logical interface.
enabled: true
entry_point: configure_bridge_domain.py
parameters:
  mgmt_ip:
    type: string
    description: The management IP address of the target device.
    required: true
    position: 0
  username:
    type: string
    description: The login user name to connect to the device.
    position: 1
  password:
    type: string
    description: THe login password to connect to the device.
    secret: true
    position: 2
  bridge_domain_id:
    type: string
    description: The Bridge-domain ID.
      Valid values are <1-4096> on SLX9140,SLX9850,SLX9540 and <1-3566> on SLX9240.
    required: true
    position: 3
  bridge_domain_service_type:
    type: string
    enum:
      - p2mp
      - p2p
    description: The bridge domain service type.
      `p2p` is valid only on SLX9850,SLX9540.
    position: 4
    default: p2mp
  vc_id:
    type: string
    description: The VC Id under the VPLS Instance. Range <1-4294967295>.
      Valid only on SLX9850,SLX9540.
    position: 5
  statistics:
    type: boolean
    description: Configure Statistics.
    position: 6
    default: true
  bpdu_drop_enable:
    type: boolean
    description: Drop BPDU packets.
      Valid only on SLX9850,SLX9540.
    position: 7
    default: false 
  local_switching:
    type: boolean
    description: Configured local switching.
      Valid only on SLX9850,SLX9540.
    position: 8
    default: false
  peer_ip:
    type: array
    description: A single or a list of IPv4/IPv6 addresses to be configured on the bridge_domain.
      IPv4, for example 10.0.0.10.
      Valid only on SLX9850,SLX9540.
    position: 9
  pw_profile_name:
    type: string
    description: The pw-profile name (Max Size - 64).
      Valid only on SLX9850,SLX9540.
    position: 10
    default: default
  intf_type:
    type: string
    description: The logical interface type. Valid Types are 'ethernet','port_channel'. For
      Example. 'ethernet' --> if all the entries in logical_interface_number are of
      type ethernet 'port_channel' --> if all the entries in logical_interface_number
      are of type port_channel 'ethernet,port_channel,ethernet,port_channel' --> If
      the entries in logical_interface_number are of mixed types.
    position: 11
  logical_interface_number:
    type: string 
    description: The physical port or port channel number list. 
      Format for the logical interfaces is <physical/port-channel number>.<number>.
      For E.g '0/34.11,21.1,0/35.1,22.1'
    position: 12
  vlan_id:
    type: string
    description: The VLAN ID to map the broadcast domain to a router interface.
      Valid range <1-4096>
    position: 13
