---
name: configure_logical_interface
pack: network_essentials
runner_type: python-script
description: This creates the logical interface under the physical/port-channel interface and
  untag/tag vlan.
enabled: true
entry_point: configure_logical_interface.py
parameters:
  mgmt_ip:
    type: string
    description: The management IP address of the target device.
    required: true
    position: 0
  username:
    type: string
    description: The login user name to connect to the device.
    position: 1
  password:
    type: string
    description: The login password to connect to the device.
    secret: true
    position: 2
  intf_type:
    type: string
    enum:
      - ethernet
      - port_channel
    default: ethernet
    description: The interface type.
    position: 3
  intf_name:
    type: string
    description: The interface Port number or Port channel number. Examples for SLX are
      1/13, 1/14.
    required: true
    position: 4
  logical_interface_number:
    type: string 
    description: The interface name of the physical port or port channel number. E.g:0/1.1 or
      7.1. Format for the logical interfaces is <physical/port-channel number>.<number>.
    required: true
    position: 5
  vlan_type:
    type: string
    enum:
      - untagged
      - tagged
      - double_tagged
    description: The VLAN tag type.
    position: 6
  vlan_id:
    type: string
    description: A single or a list of VLANIDs. VLAN ID range is 1-4090.
      If `vlan_type` is `tagged`, `vlan_id` needs to be specified.
      If `vlan_type` is `double_tagged`, `vlan_id` needs to be specified and is interpreted as outer_vlan_id..
      If `vlan_type` is `untagged`, `vlan_id` needs to be specified. Valid only on SLX9850,SLX9540.
    position: 7
  inner_vlan_id:
    type: string
    description: This configures a single VLAN or a list of Inner VLANs for the logical interface.
      Valid vlan id range <1-4090>. Valid only if `vlan_type` is `double_tagged`.
    position: 8
