---
name: get_persist_configuration_status
pack: network_essentials 
runner_type: python-script
description: This action fetches the status of persist configuration operation on the SLX devices. 
enabled: true
entry_point: get_persist_configuration_status.py 
parameters:
parameters:
  mgmt_ip:
    type: string
    description: The management IP address of the target device.
    required: true
    position: 0
  username:
    type: string
    description: The login user name to connect to the device.
    default: admin
    position: 1
  password:
    type: string
    description: The login password to connect to the device.
    default: password
    secret: true
    position: 2
  session_id:
    type: string
    description: Session id of the persist operation. 
    required: true
    position: 3
